spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8072/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

server:
  port: 8071

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka"
      fetchRegistry: true
      registerWithEureka: true
  instance:
    preferIpAddress: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

resilience4j.circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 2
