server:
  port: 8080
spring:
  application:
    name: accounts
  config:
    import: "optional:configserver:http://localhost:8072/"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    sql:
      inti:
        mode: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true


  info:
    env:
      enabled: true

info:
  app:
    name: 'Accounts'
    description: 'This is the accounts service'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8070/eureka'
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true



