server:
  port: 8080
spring:
  application:
    name: accounts
  config:
    import: "optional:configserver:http://localhost:8072/"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    sql:
      inti:
        mode: always
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    circuitbreaker:
      enabled: true

endpoints:
  shutdown:
    enabled: true


  info:
    env:
      enabled: true

info:
  app:
    name: 'Accounts'
    description: 'This is the accounts service'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8070/eureka'
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 2
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    io.github.resilience4j: DEBUG
    
resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 100
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      randomizeWaitDuration: true

